env:
  global:
    - CC_TEST_REPORTER_ID=ba0c56fa431a41c03cc4e706268941c6c9f14262626e73321d980e6ef22a2784
language: node_js
node_js:
  - 9
cache: yarn
before_install:
  - yarn global add jest
  - yarn global add codecov
install:
  - yarn
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn clean
  - yarn build
  - yarn test
  - codecov
after_script:
  - ./cc-test-reporter upload-coverage < coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
